name: Locale updates

on:
  push:
    branches:
      - master
    paths:
      - resources/locales/**

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Update skill catalog
      run: node tools/updateSkillCatalog.js
    
    - name: Update skill manifest
      run: node tools/updateSkillManifest.js
    
    - name: Commit and push changes
      run: |
        git config user.name openhab-bot
        git config user.email bot@openhab.org
        git add -A
        git commit -m "New locale updates"
        git push
